# Generated by Django 3.2.6 on 2021-08-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='progress',
            field=models.TextField(default=3, verbose_name='Достижения'),
            preserve_default=False,
        ),
    ]
