# Generated by Django 3.2.6 on 2021-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_auto_20210813_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='args',
            field=models.TextField(default=2, verbose_name='Аргумент к /start'),
            preserve_default=False,
        ),
    ]
