# Generated by Django 3.2.6 on 2021-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0003_users_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='args',
            field=models.TextField(null=True, verbose_name='Аргумент к /start'),
        ),
        migrations.AlterField(
            model_name='users',
            name='progress',
            field=models.TextField(null=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(null=True, verbose_name='Ник пользователя'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
