# Generated by Django 3.2.6 on 2021-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0005_auto_20210813_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(verbose_name='Фраза')),
            ],
            options={
                'verbose_name': 'напоминающая фраза',
                'verbose_name_plural': 'напоминающие фразы',
                'db_table': 'notify_phrases',
            },
        ),
        migrations.RenameModel(
            old_name='phrases',
            new_name='motivating_phrases',
        ),
        migrations.AlterModelOptions(
            name='motivating_phrases',
            options={'verbose_name': 'мотивирующая фраза', 'verbose_name_plural': 'мотивирующие фразы'},
        ),
        migrations.AlterModelTable(
            name='motivating_phrases',
            table='motivating_phrases',
        ),
    ]
