# Generated by Django 3.2.6 on 2021-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0008_remove_users_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('time', models.TimeField(verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'отправка по таймеру',
                'verbose_name_plural': 'отправки по таймеру',
                'db_table': 'jobs',
            },
        ),
    ]
