# Generated by Django 3.2.6 on 2021-08-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0010_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.users', to_field='chat_id'),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
