# Generated by Django 3.2.6 on 2021-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0016_alter_users_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='ID пользователя'),
        ),
        migrations.DeleteModel(
            name='progress',
        ),
    ]
