# Generated by Django 3.2.6 on 2021-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0017_auto_20210813_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
