# Generated by Django 3.2.6 on 2021-08-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0018_alter_users_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.users')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'db_table': 'progress',
            },
        ),
    ]
