# Generated by Django 3.2.6 on 2021-08-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0019_progress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='progress',
            table='progres',
        ),
    ]
