# Generated by Django 3.2.6 on 2021-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0020_alter_progress_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='chatid',
            field=models.BigIntegerField(verbose_name='123'),
        ),
        migrations.AlterModelTable(
            name='progress',
            table='progress',
        ),
    ]
