# Generated by Django 3.2.6 on 2021-08-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0021_auto_20210813_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='progress',
        ),
    ]
