# Generated by Django 3.2.6 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0023_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='chatid',
        ),
        migrations.AddField(
            model_name='progress',
            name='chat_id',
            field=models.IntegerField(default=2, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='dt',
            field=models.DateTimeField(default=3, verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='text',
            field=models.TextField(default=1, verbose_name='Достижение'),
            preserve_default=False,
        ),
    ]
