# Generated by Django 3.2.6 on 2021-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0025_delete_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ID пользователя')),
                ('dt', models.DateTimeField(verbose_name='Время')),
                ('text', models.TextField(verbose_name='Достижение')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'db_table': 'progress',
            },
        ),
    ]
